apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-rlxo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-rlxo
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-rlxo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-rlxo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-rlxo
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zoix-tenant/rhtap-demo-app/hacbs-test-project-rlxo@sha256:95c63ccbf1aceb37528c4a7b8a1dbf9fa86de3934096acbe5819e20bff5482ba
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
